trigger:
  branches:
    include:
      - Desarrollo
      - QA
      - Produccion
pr:
  branches:
    include:
      - Desarrollo
      - QA
      - Produccion
pool:
   vmImage: 'windows-latest'

variables:
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/De') }}:
    - group: Angular_GestorBacklogIA - Desarrollo
    - group: Angular_GestorBacklogIA - Desarrollo DevOps
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/QA') }}:
    - group: Angular_GestorBacklogIA - QA
    - group: Angular_GestorBacklogIA - QA DevOps
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/Prod') }}:
    - group: Angular_GestorBacklogIA - Produccion
    - group: Angular_GestorBacklogIA - Produccion DevOps

resources:
  repositories:
    - repository: templates
      type: git
      name: servicios/DevOps-ConfiguracionesGenericas
      ref: refs/tags/MasterTemplate
      endpoint: DevOpsCrossProjectConnection

stages:
  - template: azure/stages/templates/AngularTemplate.yaml@templates
