import {
  LucideArrowLeft,
  LucideAppWindow,
  LucideCalendarDays,
  LucideChartColumn,
  LucideCheck,
  LucideChevronDown,
  LucideChevronRight,
  LucideCircleCheck,
  LucideCircleX,
  LucideClipboardCheck,
  LucideEye,
  LucideEyeOff,
  LucideFileText,
  LucideFilePenLine,
  LucideFolderKanban,
  LucideHouse,
  LucideInfo,
  LucideLayoutDashboard,
  LucideLightbulb,
  LucideLink,
  LucideListChecks,
  LucideListTodo,
  LucideLockKeyhole,
  LucideLogOut,
  LucideMaximize2,
  LucideMinimize2,
  LucideMonitorCog,
  LucideMonitor,
  LucideEllipsis,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucidePencilLine,
  LucidePlus,
  LucideRefreshCw,
  LucideSave,
  LucideSearch,
  LucideSend,
  LucideScanText,
  LucideServerCog,
  LucideSmartphone,
  LucideSparkles,
  LucideTrendingUp,
  LucideTriangleAlert,
  LucideTrash2,
  LucideUserRound,
  LucideUserRoundCog,
  LucideUsersRound,
  LucideWorkflow,
  LucideZoomIn,
  LucideZoomOut,
  LucideX,
  type LucideIconData,
} from '@lucide/angular';

/** Conserva la silueta de Azure DevOps dentro del renderizador compartido. */
const ICONO_AZURE_DEVOPS = {
  name: 'AzureDevOps',
  node: [
    [
      'path',
      {
        d: 'M22.667 5.333V18.32l-5.334 4.373-8.266-3.013v2.987l-4.68-6.12 13.64 1.066V5.92Zm-4.547.653L10.467 1.333v3.054L3.44 6.453 1.333 9.16v6.147l3.014 1.333V8.76Z',
        fill: 'currentColor',
        stroke: 'none',
      },
    ],
  ],
} as const satisfies LucideIconData;

/** Catálogo semántico inicial de iconos compartidos por la aplicación. */
export const ICONOS_APLICACION = {
  agregar: LucidePlus.icon,
  asistenteIA: LucideSparkles.icon,
  aplicacionEscritorio: LucideMonitor.icon,
  aplicacionMovil: LucideSmartphone.icon,
  aplicacionWeb: LucideAppWindow.icon,
  alerta: LucideTriangleAlert.icon,
  azureDevOps: ICONO_AZURE_DEVOPS,
  backlog: LucideListTodo.icon,
  bloqueado: LucideLockKeyhole.icon,
  borrador: LucideFilePenLine.icon,
  calendario: LucideCalendarDays.icon,
  cerrar: LucideX.icon,
  cerrarSesion: LucideLogOut.icon,
  colapsarPanel: LucidePanelLeftClose.icon,
  completado: LucideCircleCheck.icon,
  confirmar: LucideCheck.icon,
  contextoProyecto: LucideFileText.icon,
  continuar: LucideChevronRight.icon,
  desplegar: LucideChevronDown.icon,
  eliminar: LucideTrash2.icon,
  enviar: LucideSend.icon,
  error: LucideCircleX.icon,
  editar: LucidePencilLine.icon,
  expandirPanel: LucidePanelLeftOpen.icon,
  inicio: LucideHouse.icon,
  informacion: LucideInfo.icon,
  enlace: LucideLink.icon,
  necesidadNegocio: LucideLightbulb.icon,
  mostrar: LucideEye.icon,
  masOpciones: LucideEllipsis.icon,
  ocultar: LucideEyeOff.icon,
  objetivos: LucideListChecks.icon,
  panel: LucideLayoutDashboard.icon,
  proyectos: LucideFolderKanban.icon,
  reintentar: LucideRefreshCw.icon,
  guardar: LucideSave.icon,
  buscar: LucideSearch.icon,
  resumen: LucideChartColumn.icon,
  alcance: LucideScanText.icon,
  equipo: LucideUsersRound.icon,
  flujo: LucideWorkflow.icon,
  roles: LucideUserRoundCog.icon,
  seguimiento: LucideTrendingUp.icon,
  tareaCompletada: LucideClipboardCheck.icon,
  tipoSolucion: LucideMonitorCog.icon,
  tipoSinInterfaz: LucideServerCog.icon,
  usuario: LucideUserRound.icon,
  volver: LucideArrowLeft.icon,
  acercar: LucideZoomIn.icon,
  alejar: LucideZoomOut.icon,
  ampliar: LucideMaximize2.icon,
  reducir: LucideMinimize2.icon,
} as const satisfies Record<string, LucideIconData>;

/** Limita los nombres permitidos a los iconos registrados. */
export type NombreIconoAplicacion = keyof typeof ICONOS_APLICACION;
